project:
  type: website
  output-dir: docs

website:
  title: "ericamarie9016.github.io"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: 
      light: minty
      dark: slate
    css: styles.css
    toc: true

editor: visual

