project:
  type: website
  output-dir: docs

website:
  title: "Erica M. Dale"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog Posts
      - href: Erica-Dale-Resume.pdf
        text: Resume
#    page-footer:
#      left:
#      - "Copyright 2022, Erica Dale"
#      right: 
#      - icon: github
#        href: http://github.com/ericamarie9016

format:
  html:
    theme: 
      - mystyles.scss
#      light: morph
#      dark: slate
#    css: styles.css
    mainfont: Lato
    toc: true

editor: visual

